app/blueprints/__init__.py
from flask import Blueprint

from .views import (delete_product, insert_products, insert_seller,
                    list_products, login, logout, sell_product,
                    update_products)

bp = Blueprint(
    "blueprints",
    __name__,
    template_folder="templates",
    static_folder="static",
    static_url_path='/app/blueprints/static/'
)

bp.add_url_rule(
    rule="/",
    view_func=login,
    endpoint='login',
    methods=['POST', 'GET'],
)
bp.add_url_rule(
    rule="/logout",
    view_func=logout,
    endpoint='logout',
    methods=['GET'],
)
bp.add_url_rule(
    rule="/list_products",
    view_func=list_products,
    endpoint='list_products',
    methods=["GET"]
)
bp.add_url_rule(
    rule="/sell_products",
    view_func=sell_product,
    methods=["GET", "POST"],
)
bp.add_url_rule(
    rule="/delete_products/<id>",
    endpoint='delete_product',
    view_func=delete_product,  # type: ignore
    methods=["GET"],
)
bp.add_url_rule(
    rule="/insert_products",
    view_func=insert_products,
    methods=["GET", "POST"],
)
bp.add_url_rule(
    rule="/update_products/<id>",
    view_func=update_products,  # type: ignore
    methods=["GET", "POST"],
)
bp.add_url_rule(
    rule="/insert_seller",
    view_func=insert_seller,
    methods=["GET", "POST"],
)


def init_app(app):
    app.register_blueprint(bp)

app/blueprints/views.py
from flask import redirect, render_template, request, session, url_for
from flask_login import login_required, login_user, logout_user

from app.extension.database import db
from app.models.forms import LoginForm
from app.models.tables import (Category, Email, PhoneNumber, Product, Size,
                               User, UserEmail, UserPhoneNumber)


def login():

    form = LoginForm()
    user = User()

    if request.method == 'POST':
        if form.validate_on_submit():

            query = user.get_user(request.form['user'])

            if query.user and query.verify_password(request.form['password']):

                session['id'] = query.id
                session['user'] = query.user
                session['cargo'] = query.roles_fk

                login_user(query)

                return redirect(url_for("blueprints.list_products"))
    return render_template("index.html", form=form)


@login_required
def logout():
    logout_user()
    session.clear()
    return redirect(url_for("blueprints.login"))

# CRUD do produto


@login_required
def list_products():

    product = Product()

    query = product.get_products()

    if "search" in request.args:

        query = product.search(str(request.args.get('search')))

    return render_template("list_products.html", product=query)


@ login_required
def sell_product():
    if request.method == "POST":

        product = Product()

        for id in request.form.getlist('sell_products'):

            product.update_product(int(id), quantity=1)

        return redirect(url_for("blueprints.list_products"))
    return redirect(url_for("log_in"))


@ login_required
def delete_product(id: int):

    query = Product()
    query.delete_product(id)

    return redirect(url_for("blueprints.list_products"))


@ login_required
def delete_products_list():
    if request.method == "POST":
        for i in range((len(request.form)//2)+1):
            form = {
                'id': f'id{i}',
                'quantity': f'quantity{i}',
                'removal': f'removal{i}'
            }
            for id in request.form.getlist(form['id']):
                for quantity in request.form.getlist(form['quantity']):
                    for removal in request.form.getlist(form['removal']):

                        product = Product.query.get(id)

                        if int(product.quantity) != 0:

                            product.quantity -= int(quantity)
                            product.removal = str(removal)
                            db.session.commit()

        return redirect(url_for("ListProducts"))

    return render_template("delete_products.html")


@login_required
def insert_products():
    if request.method == "POST":

        query = Product()

        products = {
            "title": str(request.form['title']).upper(),
            "size_fk": int(request.form['size']),
            "quantity": int(request.form['quantity']),
            "category_fk": int(request.form['category']),
            "sale_price": float(request.form['price']),
            "description": str(request.form['description']).upper(),
            "purchase_price": float(request.form['purchase_price']),
        }

        query.insert_product(**products)

    category = Category.query.order_by(Category.category).all()
    size = Size.query.order_by(Size.size).all()

    return render_template(
        "insert_products.html",
        category=category,
        size=size
    )


@login_required
def update_products(id: int):
    product = Product()
    match request.method:
        case "POST":

            return redirect(url_for("blueprints.list_products"))
        case "GET":
            query = product.get_product(id)

            return render_template('update_products.html', product=query)

# CRUD do vendedor


@login_required
def insert_seller():
    if 'id' in session and session['cargo'] in ['gerente', 'administrador']:
        if request.method == "POST":

            email = Email(
                e_mail=request.form['e_mail']
            )

            db.session.add(email)
            db.session.commit()

            phone_number_ = PhoneNumber(
                phone_number=request.form['phone_number']
            )

            db.session.add(phone_number_, email)
            db.session.commit()

            email = Email.query.order_by(
                Email.id.desc()
            ).first()
            phone_number_ = PhoneNumber.query.order_by(
                PhoneNumber.id.desc()
            ).first()

            seller = User(
                user=str(request.form['user']),
                password=request.form['password'],
                roles_fk=int(3),
            )

            db.session.add(seller)
            db.session.commit()

            seller = User.query.order_by(
                User.id.desc()
            ).first()

            user_email = UserEmail(
                user_fk=seller.id,
                e_mail_fk=int(email.id),
            )

            db.session.add(user_email)
            db.session.commit()

            user_phone_number = UserPhoneNumber(
                user_fk=seller.id,
                phone_number_fk=int(phone_number_.id),
            )

            db.session.add(user_phone_number)
            db.session.commit()

            return render_template("insert_seller.html")
    return redirect(url_for("log_in"))

app/blueprints/templates/create-account.html
{% import "partials/head.html" as componets %}
<!DOCTYPE html>
<html>

<head>
    {{ componets.head("Criar conta", "create-account.css", "passwordText.js") }}
</head>

<body>
    <section>
        <form action="{{url_for('sing_up')}}" method="POST">

            <legend>EdControle</legend>
            <div class="container-input">

                <div class="fa-solid fa-user">
                    <input name="user" type="text" required placeholder="Usuário" />
                </div>

                <div class="fa-solid fa-phone">
                    <input name="phone_number" type="text" required placeholder="Número de telefone" />
                </div>

                <div class="fa-solid fa-envelope">
                    <input name="e_mail" type="email" required placeholder=" E-mail" />
                </div>


                <div class="fa-solid fa-lock">
                    <input type="password" name="password" required placeholder="Senha" />
                    <span class="fa-solid fa-eye-slash" onclick="Password()"></span>
                </div>

            </div>

            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />

            <button>Criar conta</button>

        </form>
    </section>

</body>

</html>

app/blueprints/templates/delete_products.html
{% import "partials/head.html" as head %}
{% import "partials/header.html" as header %}
<!DOCTYPE html>
<html>

<head lang="pt-BR">
  {{ head.head("Remover Produto", "delete_products.css", "input.js") }}

<body>
  <section>
    {{ header.header(session['user']) }}
    <main>
      <form action="/delete_products" method="POST">
        <div id="field1">
          <div>
            <label for="id1"></label>
            <input required placeholder="Código do produto" name="id1" type="text" id="id1">
          </div>
          <div>
            <label for="quantity1"></label>
            <input required placeholder="Quantidade" name="quantity1" type="text" id="quantity1" />
          </div>
          <div>
            <label for="removal1"></label>
            <input required placeholder="Motivo da remoção" name="removal1" type="text" id="removal1" />
          </div>
          <button type="button" onclick="AddField()" class="fa-solid fa-plus"></button>
        </div>
        <div>
          <button type="submit">CADASTRAR</button>
        </div>
      </form>
    </main>
  </section>
</body>

</html>

app/blueprints/templates/index.html
{% import "partials/head.html" as componets %}
<!DOCTYPE html>
<html>
{{ componets.head("Página inicial", "index.css", "passwordText.js") }}

<body>
  <section>
    <form action="{{url_for('blueprints.login')}}" method="POST">

      <legend>EdControle</legend>
      <div class="container-input">

        <div class="fa-solid fa-user">
          {{form.user}}
        </div>
        {% if form.errors.user %}
        {{form.errors.user}}
        {%endif%}
        <div class="fa-solid fa-lock">
          {{form.password}}
          <span class="fa-solid fa-eye-slash" onclick="Password()"></span>
        </div>

      </div>

      <div class="container-buttons">
        {{form.sumbit}}
      </div>
      {{form.csrf_token}}
    </form>
  </section>
</body>

</html>

app/blueprints/templates/insert_products.html
{% import "partials/head.html" as head %}
{% import "partials/header.html" as header %}
<!DOCTYPE html>
<html>
{{ head.head("Cadastrar Produto", "insert_products.css") }}

<body>
  <section>
    {{ header.header(session['user']) }}
    <main>
      <form action="{{url_for('blueprints.insert_products')}}" method="post">
        <div>
          <label for="title"></label>
          <input name="title" id="title" type="text" required placeholder="Nome do produto" />
        </div>

        <div>
          <label for="size"></label>
          <select required name="size" id="size">
            <option value="" disabled selected hidden>Tamanho do produto</option>
            {% for s in size %}
            <option value="{{s.id}}">{{s.size}}</option>
            {% endfor %}
          </select>
        </div>

        <div>
          <label for="category"></label>
          <select required name="category" id="category">
            <option value="" disabled selected hidden>Categoria do produto</option>
            {% for c in category %}
            <option value="{{c.id}}">{{c.category}}</option>
            {% endfor %}
          </select>
        </div>

        <div>
          <label for="quantity"></label>
          <input name="quantity" type="number" id="quantity" required placeholder="Quantidade do produto" />
        </div>

        <div>
          <label for="purchase_price"></label>
          <input name="purchase_price" id="purchase_price" type="number" required placeholder="Preço de compra" />
        </div>

        <div>
          <label for="price"></label>
          <input name="price" type="number" id="price" required placeholder="Preço de venda" />
        </div>

        <div>
          <label for="description"></label>
          <input name="description" type="text" required placeholder="Descrição do produto" />
        </div>

        <button>CADASTRAR</button>
      </form>
    </main>
  </section>
</body>

</html>

app/blueprints/templates/insert_seller.html
{% import "componets.html" as componets %}
<!DOCTYPE html>
<html>
{{ componets.head("Cadastrar Vendedor", "insert_seller.css") }}

<body>
  <section>
    {{ componets.header(session['user']) }}
    <main>
      <h1>CADASTRAR VENDEDOR</h1>
      <form action="{{url_for('insert_seller')}}" method="post">
        <div>
          <label for="">Usuário</label>
          <input name="user" type="text" />
        </div>
        <div>
          <label for="">Número de celular</label>
          <input name="phone_number" type="text" />
        </div>
        <div>
          <label for="">E-mail</label>
          <input name="e_mail" type="text" />
        </div>
        <div>
          <label for="">Senha</label>
          <input name="password" type="text" />
        </div>
        <button>CADASTRAR</button>
      </form>
    </main>
  </section>
</body>

</html>

app/blueprints/templates/list_products.html
{% import "partials/head.html" as head %} {% import "partials/header.html" as
header %}
<!DOCTYPE html>
<html>
  {{ head.head("Estoque", "list_products.css") }}

  <body>
    <section>
      {{ header.header(session['user']) }}
      <main>
        <form
          action="{{url_for('blueprints.sell_product')}}"
          method="POST"
          class="table"
        >
          <div class="button-area">
            <a href="{{url_for('blueprints.insert_products')}}">
              <span class="fa-solid fa-plus"></span>
              Adicionar
            </a>
          </div>
          <div class="form">
            <table>
              <thead>
                <tr>
                  <th></th>
                  <th>Código</th>
                  <th>Nome</th>
                  <th>Tamanho</th>
                  <th>Quantidade</th>
                  <th>Situação do Estoque</th>
                  <th>Seção</th>
                  <th>Preço de compra</th>
                  <th>Preço de venda</th>
                  <th>Ações</th>
                </tr>
              </thead>
              <tbody>
                {% for p in product %}
                <tr>
                  <td>
                    <input
                      name="sell_products"
                      value="{{p.id}}"
                      type="checkbox"
                    />
                  </td>
                  <td>{{p.id}}</td>
                  <td>{{p.title}}</td>
                  <td>{{p.size}}</td>
                  <td>{{p.quantity}}</td>

                  <td>_</td>
                  <td>{{p.category}}</td>
                  <td>{{p.purchase_price}}</td>
                  <td>{{p.sale_price}}</td>
                  <td>
                    <a
                      class="fa-solid fa-trash"
                      href="{{url_for('blueprints.delete_product', id=p.id)}}"
                    ></a>
                    <a
                      class="fa-solid fa-square-pen"
                      href="{{url_for('blueprints.update_products', id=p.id)}}"
                    ></a>
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <div class="button-vender">
            <button>Vender</button>
          </div>
        </form>
      </main>
    </section>
  </body>
</html>

app/blueprints/templates/partials/head.html
{% macro head(title, css, js) %}

<head lang="pt-BR">
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{{title}} - EdControle</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&display=swap"
        rel="stylesheet" />
    <link rel="stylesheet" type="text/css" media="screen"
        href="{{url_for('.static', filename='css/{0}'.format(css)) }}" />
    {% if js %}
    <script src="{{url_for('.static', filename='js/{0}'.format(js))}}" defer></script>
    {% endif %}
    <script src="https://kit.fontawesome.com/8544c965ee.js" crossorigin="anonymous"></script>
</head>

{% endmacro %}

app/blueprints/templates/partials/header.html
{% macro header(user) %}

<header>
    <!--   <img src="{{url_for('static', filename='#')}}" alt="Logo " /> -->
    <span><a href="{{url_for('blueprints.list_products')}}">EdControle</a></span>
    <div class="container-search">
        <form action="{{url_for('blueprints.list_products')}}" method="GET">
            <div>
                <label class="fa-solid fa-magnifying-glass" for="search"></label>
                <input type="text" name="search" id="search" placeholder="Pesquisar" />
            </div>
        </form>
    </div>
    <nav>
        <li>
            <span>{{user}}</span>
            <ul>
                <li>
                    <a href="#">Configurações</a>
                </li>
                <li>
                    <a href="{{url_for('blueprints.logout')}}">Sair</a>
                </li>
            </ul>
        </li>
        <span>
            <a class="fa-solid fa-house-user" href="{{url_for('blueprints.list_products')}}"></a>
        </span>
    </nav>

</header>

{% endmacro %}

app/blueprints/templates/update_products.html
{% import "partials/head.html" as head %} {% import "partials/header.html" as
header %}
<!DOCTYPE html>
<html>
  {{ head.head("Cadastrar Produto", "insert_products.css") }}

  <body>
    <section>
      {{ header.header(session['user']) }}
      <main>
        <form
          action="{{url_for('blueprints.update_products', id=2)}}"
          method="post"
        >
          <div>
            <label for="title"></label>
            <input
              name="title"
              id="title"
              type="text"
              value="{{product.title}}"
            />
          </div>
          <div>
            <label for="size"></label>
            <input name="size" type="text" id="size" value="{{product.size}}" />
          </div>

          <div>
            <label for="category"></label>
            <input
              name="category"
              type="text"
              id="category"
              value="{{product.category}}"
            />
          </div>

          <div>
            <label for="quantity"></label>
            <input
              name="quantity"
              type="text"
              id="quantity"
              value="{{product.quantity}}"
            />
          </div>

          <div>
            <label for="purchase_price"></label>
            <input
              name="purchase_price"
              id="purchase_price"
              type="text"
              value="{{product.purchase_price}}"
            />
          </div>

          <div>
            <label for="price"></label>
            <input
              name="price"
              type="text"
              id="price"
              value="{{product.sale_price}}"
            />
          </div>

          <div>
            <label for="description"></label>
            <input
              name="description"
              type="text"
              id="description"
              value="{{product.description}}"
            />
          </div>

          <button>CADASTRAR</button>
        </form>
      </main>
    </section>
  </body>
</html>